server.port=8081
spring.application.name=tarot-backend
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./src/main/webapp/